export type Sku = { id: string; name: string; family: "A" | "B" | "C" | "D" | "E" | "F"; unitOfWork: string; priceUsd: number; atomic: string; free: boolean; mcpTool: string; httpPath: string; description: string; whenToUse: string; whenNot: string; };
function atomicFromUsd(usd: number): string { return String(Math.round(usd * 1_000_000)); }
export const SKUS: Sku[] = [
  { id: "oracle_health", name: "Health + capability card", family: "E", unitOfWork: "one liveness + menu snapshot", priceUsd: 0, atomic: "0", free: true, mcpTool: "oracle_health", httpPath: "/api/health", description: "Free discovery. Returns live tools, networks, payTo truncated, facilitator, and connect URLs.", whenToUse: "First contact.", whenNot: "Not a ranking." },
  { id: "oracle_pricing", name: "Pricing menu", family: "E", unitOfWork: "one current menu", priceUsd: 0, atomic: "0", free: true, mcpTool: "oracle_pricing", httpPath: "/api/health", description: "Free current SKU menu.", whenToUse: "Before paying.", whenNot: "Not a forecast." },
  { id: "oracle_ask", name: "Protocol how-to", family: "F", unitOfWork: "one bounded counsel answer", priceUsd: 0.1, atomic: atomicFromUsd(0.1), free: false, mcpTool: "oracle_ask", httpPath: "/api/v1/consult", description: "Short x402 / MCP / A2A how-to.", whenToUse: "Known question under $0.10.", whenNot: "Not a demand cycle." },
  { id: "oracle_diagnose_402", name: "402 handshake diagnosis", family: "B", unitOfWork: "one parsed 402 post-mortem", priceUsd: 0.5, atomic: atomicFromUsd(0.5), free: false, mcpTool: "oracle_diagnose_402", httpPath: "/api/v1/consult", description: "Paste headers. Returns LIVE | DECLARED_ONLY | MISCONFIGURED | DEAD.", whenToUse: "Claims x402.", whenNot: "Not settlement evidence." },
  { id: "oracle_probe_call", name: "Live call probe", family: "A", unitOfWork: "one unpaid knock", priceUsd: 0.25, atomic: atomicFromUsd(0.25), free: false, mcpTool: "oracle_probe_call", httpPath: "/api/v1/demand", description: "Knock a URL or Agent Card.", whenToUse: "Need live-402 truth.", whenNot: "Not a snippet rank." },
  { id: "oracle_demand_cycle", name: "Demand cycle", family: "E", unitOfWork: "one dated demand report envelope", priceUsd: 5, atomic: atomicFromUsd(5), free: false, mcpTool: "oracle_demand_cycle", httpPath: "/api/v1/demand", description: "Tables A/B/C demand cycle.", whenToUse: "Allocate budget.", whenNot: "Not a scrape." },
  { id: "oracle_review_mcp", name: "MCP production review", family: "B", unitOfWork: "one zero-error patch plan", priceUsd: 3, atomic: atomicFromUsd(3), free: false, mcpTool: "oracle_review_mcp", httpPath: "/api/v1/consult", description: "Repo or tool defs to patch plan.", whenToUse: "Shipping a server.", whenNot: "Not a chatbot." },
  { id: "oracle_bazaar_rewrite", name: "Bazaar metadata rewrite", family: "E", unitOfWork: "one ranking-ready schema pack", priceUsd: 1.5, atomic: atomicFromUsd(1.5), free: false, mcpTool: "oracle_bazaar_rewrite", httpPath: "/api/v1/consult", description: "Rewrite descriptions and inputSchema.", whenToUse: "Live but unranked.", whenNot: "Does not create volume." },
  { id: "complete_oracle_task", name: "Composite A2A task", family: "C", unitOfWork: "review + discovery + verify script", priceUsd: 15, atomic: atomicFromUsd(15), free: false, mcpTool: "complete_oracle_task", httpPath: "/api/v1/consult", description: "Multi-step executor task.", whenToUse: "Shippable packet.", whenNot: "Not a one-liner." },
];
export function skuById(id: string) { return SKUS.find((s) => s.id === id); }
export function paidSkus() { return SKUS.filter((s) => !s.free); }
export function freeSkus() { return SKUS.filter((s) => s.free); }
